version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: shopstack

    command: --default-authentication-plugin=mysql_native_password

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql   # ✅ DB storage (IMPORTANT)

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmysql"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 40s

    networks:
      - shop-network


  backend:
    build: ./backend
    container_name: backend-app
    restart: always

    ports:
      - "8000:8000"

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_DB: shopstack
      MYSQL_PORT: 3306

      SECRET_KEY: your_secret_key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    volumes:
      - backend_logs:/app/logs   # ✅ backend logs storage (optional)
      - backend_uploads:/app/uploads  # ✅ if you upload files

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - shop-network


  frontend:
    build: ./frontend
    container_name: frontend-app
    restart: always

    ports:
      - "3000:80"

    depends_on:
      - backend

    networks:
      - shop-network


# =========================
# STORAGE (VOLUMES)
# =========================
volumes:
  mysql_data:        # ✅ keeps database even if container deleted
  backend_logs:      # optional
  backend_uploads:   # optional
  frontend_cache:    # optional


# =========================
# NETWORK
# =========================
networks:
  shop-network:
    driver: bridge